[project]
name = "villainous-automa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "XBigTK13X", email = "xbigtk13x@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow==12.1.0",
    "pypdf==6.5.0",
]

[project.scripts]
villainous-automa = "villainous_automa:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
